coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

ignore:
  - "*/tests/*"
  - "*/management/*"
  - "*/migrations/*"
  - "venv/*"
  - "env/*"
  - "mysite/wsgi.py"
  - "manage.py"
