# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "code",
                    models.URLField(blank=True, null=True, verbose_name="demo code"),
                ),
                ("slides", models.URLField(verbose_name="slides URL")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.Event"
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="djangoarticle",
            name="author",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.RemoveField(
            model_name="pythonarticle",
            name="author",
        ),
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="DjangoArticle",
        ),
        migrations.DeleteModel(
            name="PythonArticle",
        ),
    ]
