# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20180605_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="date_presented",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
