# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_talk_presenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="talk_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
