# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_talk_talk_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talk",
            name="talk_date",
        ),
    ]
