# Generated by Django 3.0.3 on 2020-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talk",
            name="cover",
            field=models.URLField(default="http://placehold.it/750x300"),
        ),
    ]
