# Generated by Django 3.0.3 on 2020-06-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_auto_20200627_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.Category",
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="topic",
            field=models.CharField(default="Django", max_length=200),
        ),
    ]
