# Generated by Django 3.0.3 on 2020-06-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_auto_20200627_1608"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
