# Generated by Django 3.0.3 on 2020-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_talk_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.URLField(default='http://placehold.it/750x300'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.URLField(default='http://placehold.it/750x300'),
        ),
    ]
