# Generated by Django 3.0.3 on 2020-08-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_auto_20200627_1927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="summary",
        ),
    ]
