# Generated by Django 3.0.14 on 2021-04-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210428_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='alt_text',
            field=models.CharField(default='Post Cover', max_length=100, verbose_name='Alt Text'),
        ),
    ]
