# Generated by Django 4.0.4 on 2022-05-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210428_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_past',
        ),
    ]
