# Generated by Django 4.0.4 on 2022-06-24 13:50

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_remove_category_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="tip",
            field=markdownfield.models.MarkdownField(rendered_field="text_rendered"),
        ),
    ]
