name: CodeCov

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - [3.9]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: mysql_password
          MYSQL_DATABASE: mysql
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Generate Report
        run: |
          coverage run -m pytest
          coverage xml
        env:
          DATABASE_ENGINE: django.db.backends.mysql
          DATABASE_NAME: github_actions
          DATABASE_USER: root
          DATABASE_PASSWORD: mysql_password
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}

    - name: Upload Coverage to Codecov
    - uses: codecov/codecov-action@v2
