name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - 3.9
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: mysql_password
          MYSQL_DATABASE: mysql
        ports:
          - 3306:3306
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('package.json') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

        env:
          DATABASE_ENGINE: django.db.backends.mysql
          DATABASE_NAME: mysql
          DATABASE_USER: root
          DATABASE_PASSWORD: mysql_password
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run Tests
        run: |
          coverage run -m pytest
        env:  
          DATABASE_ENGINE: django.db.backends.mysql
          DATABASE_NAME: mysql
          DATABASE_USER: root
          DATABASE_PASSWORD: mysql_password
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
